# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_id', models.CharField(help_text='A Unique ID for this plan, which will be                                          used throughtout the API.', max_length=255)),
                ('amount', models.IntegerField(default=2000)),
                ('currency', models.CharField(default='usd', max_length=255)),
                ('interval', models.CharField(default='month', max_length=255)),
            ],
        ),
    ]
