# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0002_remove_credit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
