# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_credit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_id', models.CharField(help_text='A Unique ID for this plan, which will be                                          used throughtout the API.', max_length=255)),
                ('amount', models.IntegerField(default=2000)),
                ('currency', models.CharField(default='usd', max_length=255)),
                ('interval', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='fisttime_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='point',
            field=models.IntegerField(default=200),
        ),
    ]
