# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_plan_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='point',
            new_name='credit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='fisttime_user',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='user',
        ),
    ]
