# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170715_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_sid',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account SID'),
        ),
    ]
