# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, default='account name', max_length=255, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_sid',
            field=models.CharField(blank=True, default='twilio_sid', max_length=255, verbose_name='Account SID'),
        ),
    ]
