# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20170726_2309'),
        ('users', '0009_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plan.Credit'),
        ),
    ]
